name: Nix

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: cachix/install-nix-action@v12
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210126_f15f0b8/install
        extra_nix_config: |
          experimental-features = nix-command flakes
    - uses: actions/checkout@v2
    - name: Build
      run: |
        nix develop -c cargo build --verbose --all-targets
        nix develop -c cargo build --verbose --all-targets --release
    - name: Run tests
      run: |
        nix develop -c cargo test --verbose
        nix develop -c cargo test --verbose --release
