name: Nix

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: cachix/install-nix-action@v14.1
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210415_76980a1/install
        extra_nix_config: |
          experimental-features = nix-command flakes
    - uses: actions/checkout@v3
    - uses: cachix/cachix-action@v13
      with:
        name: jrestivo
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Build
      run: |
        nix build .#flake_generator-debug -L --show-trace
        nix build .#flake_generator -L --show-trace
    - name: Run tests
      run: |
        nix develop -c check
